Web/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Eshop.Domain.Domain;
using Repository;
using Project.Service.Interface;
using Service.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Service.Implementation;
using Domain.Identity_Models;

namespace Web.Controllers
{
    public class BooksController : Controller
    {
        private readonly IBookService _bookService;
        private readonly IAuthorService _authorService;
        private readonly IPublisherService _publisherService;
        private readonly UserManager<IntegratedSystemsUser> _userManager;
        private readonly IShoppingCartService _shoppingCartService;

        public BooksController(IBookService bookService, IAuthorService authorService, IPublisherService publisherService,
            UserManager<IntegratedSystemsUser> userManager, IShoppingCartService shoppingCartService)
        {
            _bookService = bookService;
            _authorService = authorService;
            _publisherService = publisherService;
            _userManager = userManager;
            _shoppingCartService = shoppingCartService;
        }
        // GET: Books
        public IActionResult Index(string searchString)
        {
            var books=_bookService.GetAllBooks();
            if (!string.IsNullOrEmpty(searchString))
            {
                books = _bookService.GetBooksByName(searchString);
            }

            return View(books);
        }

        // GET: Books/Details/5
        public IActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = _bookService.GetDetailsForBook(id);
            if (book == null)
            {
                return NotFound();
            }
            List<Author>? authors = book?.Authors?.ToList();
            ViewData["Publisher"] = book.Publisher;
            ViewData["Authors"]=authors;
            return View(book);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> AddToCart(Guid id, int quantity)
        {
            var book = _bookService.GetDetailsForBook(id);
            if (book == null)
            {
                return NotFound();
            }

            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return Challenge();
            }

            try
            {
                _shoppingCartService.AddToCart(user.Id, id, quantity);
                TempData["Success"] = $"{book.Title} has been added to your cart.";
            }
            catch (Exception ex)
            {
                TempData["Error"] = "There was an error adding the item to your cart.";
            }

            return RedirectToAction(nameof(Details), new { id = book.Id });
        }
        // GET: Books/Create
        public IActionResult Create()
        {
            ViewBag.Authors = new SelectList(_authorService.GetAuthorList(), "Id", "Name");
            ViewBag.Publishers = new SelectList(_publisherService.GetAllPublishers(), "Id", "Name");
            return View();
        }

        // POST: Books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize] 
        public async Task<IActionResult> Create([Bind("ISBN,Title,Description,Date,Price,PictureUrl,Id,AuthorIds,PublisherId")] Book book)
        {
            if (ModelState.IsValid)
            {

                var user = await _userManager.GetUserAsync(User);
                if (user == null)
                {
                    return Challenge();
                }

                book.UserId = user.Id;

                var selectedAuthors = _authorService.GetAuthorList().Where(a => book.AuthorIds.Contains(a.Id));
                var publisher = _publisherService.GetDetailsForPublisher(book.PublisherId);
                if (selectedAuthors.Any())
                {
                    book.Authors = selectedAuthors.ToList();
                    foreach (Author a in selectedAuthors)
                    {
                        if (a.Books == null)
                        {
                            a.Books = new List<Book>();
                        }
                        a.Books.Add(book);
                    }
                }
                if (publisher != null)
                {
                    book.Publisher = publisher;
                    if (publisher.Books == null)
                    {
                        publisher.Books = new List<Book>();
                    }
                    publisher.Books.Add(book);
                }
                _bookService.CreateNewBook(book);
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Authors = new SelectList(_authorService.GetAuthorList(), "Id", "Name");
            ViewBag.Publishers = new SelectList(_publisherService.GetAllPublishers(), "Id", "Name");
            return View(book);
        }

        // GET: Books/Edit/5
        public IActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = _bookService.GetDetailsForBook(id);
            if (book == null)
            {
                return NotFound();
            }

            ViewBag.Authors = new SelectList(_authorService.GetAuthorList(), "Id", "Name");
            ViewBag.Publishers = new SelectList(_publisherService.GetAllPublishers(), "Id", "Name");
            return View(book);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(Guid id, [Bind("ISBN,Title,Description,Date,Price,PictureUrl,Id, AuthorIds, PublisherId")] Book book)
        {
            if (id != book.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var user = await _userManager.GetUserAsync(User);
                    if (user == null)
                    {
                        return Challenge();
                    }

                    book.UserId = user.Id;

                    var existingBook = _bookService.GetDetailsForBook(id);
                    if (existingBook == null)
                    {
                        return NotFound();
                    }

                    // Handle Authors
                    var selectedAuthors = _authorService.GetAuthorList().Where(a => book.AuthorIds.Contains(a.Id));

                    // Remove book from old authors' Books collections
                    if (existingBook.Authors != null)
                    {
                        foreach (var oldAuthor in existingBook.Authors)
                        {
                            oldAuthor.Books?.Remove(existingBook);
                        }
                    }

                    // Add book to new authors' Books collections
                    existingBook.Authors = selectedAuthors.ToList();
                    foreach (var newAuthor in selectedAuthors)
                    {
                        if (newAuthor.Books == null)
                        {
                            newAuthor.Books = new List<Book>();
                        }
                        newAuthor.Books.Add(existingBook);
                    }

                    // Handle Publisher
                    if (existingBook.PublisherId != book.PublisherId)
                    {
                        // Remove from old publisher's Books collection
                        if (existingBook.Publisher != null)
                        {
                            existingBook.Publisher.Books?.Remove(existingBook);
                        }

                        // Add to new publisher's Books collection
                        var newPublisher = _publisherService.GetDetailsForPublisher(book.PublisherId);
                        if (newPublisher != null)
                        {
                            existingBook.Publisher = newPublisher;
                            if (newPublisher.Books == null)
                            {
                                newPublisher.Books = new List<Book>();
                            }
                            newPublisher.Books.Add(existingBook);
                        }
                    }
                    existingBook.UserId=user.Id;
                    existingBook.ISBN = book.ISBN;
                    existingBook.Title = book.Title;
                    existingBook.Description = book.Description;
                    existingBook.Date = book.Date;
                    existingBook.Price = book.Price;
                    existingBook.PictureUrl = book.PictureUrl;

                    _bookService.UpdateExistingBook(existingBook);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookExists(book.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

Web/Controllers/PublishersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Eshop.Domain.Domain;
using Repository;
using Service.Interface;

namespace Web.Controllers
{
    public class PublishersController : Controller
    {
        private readonly IPublisherService _publisherService;

        public PublishersController(IPublisherService publisherService)
        {
            _publisherService = publisherService;
        }

        // GET: Publishers
        public IActionResult Index()
        {
            return View(_publisherService.GetAllPublishers());
        }

        // GET: Publishers/Details/5
        public IActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var publisher = _publisherService.GetDetailsForPublisher(id);
            if (publisher == null)
            {
                return NotFound();
            }

            return View(publisher);
        }

        // GET: Publishers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Publishers/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Name,Id")] Publisher publisher)
        {
            if (ModelState.IsValid)
            {
                _publisherService.CreateNewPublisher(publisher);
                return RedirectToAction("index", "Books");
            }
            return View(publisher);
        }

        // GET: Publishers/Edit/5
        public IActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var publisher = _publisherService.GetDetailsForPublisher(id);
            if (publisher == null)
            {
                return NotFound();
            }
            return View(publisher);
        }

        // POST: Publishers/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Guid id, [Bind("Name,Id")] Publisher publisher)
        {
            if (id != publisher.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _publisherService.UpdateExistingPublisher(publisher);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PublisherExists(publisher.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("index", "Books");
            }
            return View(publisher);
        }

        // GET: Publishers/Delete/5
        public IActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var publisher = _publisherService.GetDetailsForPublisher(id);
            if (publisher == null)
            {
                return NotFound();
            }

            return View(publisher);
        }

        // POST: Publishers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(Guid id)
        {
            _publisherService.DeletePublisher(id);
            return RedirectToAction("index", "Books");
        }

        private bool PublisherExists(Guid id)
        {
            return _publisherService.GetAllPublishers().Any(e => e.Id == id);
        }
    }
}

Web/Views/Books/Create.cshtml
@model Eshop.Domain.Domain.Book
@{
    ViewData["Title"] = "Create New Book";
}

<div class="form-container">
    <div class="form-header">
        <h1>Create New Book</h1>
        <a asp-action="Index" class="back-link">
            <i class="fas fa-arrow-left"></i> Back to List
        </a>
    </div>

    <div class="form-content">
        <form asp-action="Create" class="book-form">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-grid">
                <div class="form-group">
                    <label asp-for="ISBN" class="control-label">ISBN</label>
                    <input asp-for="ISBN" class="form-control" placeholder="Enter ISBN" />
                    <span asp-validation-for="ISBN" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Title" class="control-label">Title</label>
                    <input asp-for="Title" class="form-control" placeholder="Enter book title" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>

                <div class="form-group full-width">
                    <label asp-for="Description" class="control-label">Description</label>
                    <textarea asp-for="Description" class="form-control" rows="4" placeholder="Enter book description"></textarea>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Date" class="control-label">Publication Date</label>
                    <input asp-for="Date" class="form-control" type="date" />
                    <span asp-validation-for="Date" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Price" class="control-label">Price</label>
                    <input asp-for="Price" class="form-control" placeholder="Enter price" />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>

                <div class="form-group full-width">
                    <label asp-for="PictureUrl" class="control-label">Picture URL</label>
                    <input asp-for="PictureUrl" class="form-control" placeholder="Enter image URL" />
                    <span asp-validation-for="PictureUrl" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Authors" class="control-label">Authors</label>
                    <div class="select-with-action">
                        <select asp-for="AuthorIds" asp-items="ViewBag.Authors" class="form-control" multiple>
                        </select>
                        <a asp-controller="Authors" asp-action="Create" class="btn btn-outline-primary add-new-btn">
                            <i class="fas fa-plus"></i> New Author
                        </a>
                    </div>
                </div>

                <div class="form-group">
                    <label asp-for="Publisher" class="control-label">Publisher</label>
                    <select asp-for="PublisherId" asp-items="ViewBag.Publishers" class="form-control">
                        <option value="">-- Select Publisher --</option>
                    </select>
                    <a asp-controller="Publishers" asp-action="Create" class="btn btn-outline-primary add-new-btn">
                        <i class="fas fa-plus"></i> New Publisher
                    </a>
                </div>
            </div>

            <div class="form-actions">
                <button type="submit" class="btn btn-primary">
                    <i class="fas fa-save"></i> Create Book
                </button>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Web/Views/Books/Delete.cshtml
@model Eshop.Domain.Domain.Book

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Book</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ISBN)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ISBN)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PictureUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PictureUrl)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Web/Views/Books/Details.cshtml
@using Eshop.Domain.Domain
@model Eshop.Domain.Domain.Book
@using Domain.Identity_Models
@using Microsoft.AspNetCore.Identity
@inject UserManager<IntegratedSystemsUser> UserManager
@{
    ViewData["Title"] = Model.Title;
    var publisher = ViewData["Publisher"] as Publisher;
    var authors = ViewData["Authors"] as List<Author>;
}

@if (TempData["Success"] != null)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        @TempData["Success"]
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}
@if (TempData["Error"] != null)
{
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        @TempData["Error"]
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}

<div class="book-details-container">
    <div class="book-details-header">
        <a asp-action="Index" class="back-link">
            <i class="fas fa-arrow-left"></i> Back to Books
        </a>
    </div>

    <div class="book-details-content">
        <div class="book-image-section">
            <img src="@Model.PictureUrl" alt="@Model.Title" class="book-detail-image">
            <div class="book-price-tag">$@(Model.Price?.ToString("F2") ?? "0.00")</div>
        </div>

        <div class="book-info-section">
            <h1 class="book-title">@Model.Title</h1>

            <div class="book-meta">
                <div class="meta-item">
                    <i class="fas fa-barcode"></i>
                    <span>ISBN: @Model.ISBN</span>
                </div>
                <div class="meta-item">
                    <i class="fas fa-calendar-alt"></i>
                    <span>Published: @(Model.Date?.ToString("MMMM dd, yyyy") ?? "N/A")</span>
                </div>
            </div>

            <div class="book-authors">
                <h3>Authors</h3>
                @if (Model.Authors != null && Model.Authors.Any())
                {
                    <div class="author-list">
                        @foreach (var author in Model.Authors)
                        {
                            <a asp-controller="Authors" asp-action="Details" asp-route-id="@author.Id" class="author-tag">
                                <i class="fas fa-user"></i> @author.Name
                            </a>
                        }
                    </div>
                }
                else
                {
                    <span class="text-muted">No Authors Listed</span>
                }
            </div>

            <div class="book-publisher">
                <h3>Publisher</h3>
                <span class="publisher-name">@(Model.Publisher?.Name ?? "No Publisher")</span>
            </div>

            <div class="book-description">
                <h3>Description</h3>
                <p>@Model.Description</p>
            </div>

            <div class="book-actions">
                @if (User.Identity.IsAuthenticated)
                {
                    <form asp-action="AddToCart" asp-route-id="@Model.Id" method="post" class="add-to-cart-form">
                        @Html.AntiForgeryToken()
                        <div class="quantity-control">
                            <button type="button" class="qty-btn" onclick="decrementQuantity()">-</button>
                            <input type="number" name="quantity" id="quantity" value="1" min="1" max="99" required />
                            <button type="button" class="qty-btn" onclick="incrementQuantity()">+</button>
                        </div>
                        <button type="submit" class="add-to-cart-btn">
                            <i class="fas fa-shopping-cart"></i> Add to Cart
                        </button>
                    </form>
                }
                else
                {
                    <div class="login-prompt">
                        <i class="fas fa-lock"></i>
                        <p>Please <a asp-area="Identity" asp-page="/Account/Login">log in</a> to add items to your cart.</p>
                    </div>
                }

                @if (User.Identity.IsAuthenticated && (Model.UserId == UserManager.GetUserId(User) || User.IsInRole("Admin"))){
                    <div class="admin-actions">
                        <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-warning">
                            <i class="fas fa-edit"></i> Edit Book
                        </a>
                        <a asp-action="Delete" asp-route-id="@Model?.Id" class="btn btn-danger">
                            <i class="fas fa-trash"></i> Delete Book
                        </a>
                    </div>
                }
                
            </div>
        </div>
    </div>
</div>

Web/Views/Books/Edit.cshtml
@model Eshop.Domain.Domain.Book
@{
    ViewData["Title"] = "Edit Book";
}

<div class="form-container">
    <div class="form-header">
        <h1>Edit Book</h1>
        <a asp-action="Index" class="back-link">
            <i class="fas fa-arrow-left"></i> Back to List
        </a>
    </div>

    <div class="form-content">
        <form asp-action="Edit" class="book-form">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-grid">
                <div class="form-group">
                    <label asp-for="ISBN" class="control-label">ISBN</label>
                    <input asp-for="ISBN" class="form-control" placeholder="Enter ISBN" />
                    <span asp-validation-for="ISBN" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Title" class="control-label">Title</label>
                    <input asp-for="Title" class="form-control" placeholder="Enter book title" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>

                <div class="form-group full-width">
                    <label asp-for="Description" class="control-label">Description</label>
                    <textarea asp-for="Description" class="form-control" rows="4" placeholder="Enter book description"></textarea>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Date" class="control-label">Publication Date</label>
                    <input asp-for="Date" class="form-control" type="date" />
                    <span asp-validation-for="Date" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Price" class="control-label">Price</label>
                    <input asp-for="Price" class="form-control" placeholder="Enter price" />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>

                <div class="form-group full-width">
                    <label asp-for="PictureUrl" class="control-label">Picture URL</label>
                    <input asp-for="PictureUrl" class="form-control" placeholder="Enter image URL" />
                    <span asp-validation-for="PictureUrl" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Authors" class="control-label">Authors</label>
                    <div class="select-with-action">
                        <select asp-for="AuthorIds" asp-items="ViewBag.Authors" class="form-control" multiple>
                        </select>
                        <a asp-controller="Authors" asp-action="Create" class="btn btn-outline-primary add-new-btn">
                            <i class="fas fa-plus"></i> New Author
                        </a>
                    </div>
                </div>

                <div class="form-group">
                    <label asp-for="Publisher" class="control-label">Publisher</label>
                    <select asp-for="PublisherId" asp-items="ViewBag.Publishers" class="form-control">
                        <option value="">-- Select Publisher --</option>
                    </select>
                </div>
            </div>

            <div class="form-actions">
                <button type="submit" class="btn btn-primary">
                    <i class="fas fa-save"></i> Save Changes
                </button>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Web/Views/Books/Index.cshtml
@using Domain.Identity_Models
@using Microsoft.AspNetCore.Identity
@inject UserManager<IntegratedSystemsUser> UserManager
@model IEnumerable<Eshop.Domain.Domain.Book>
@{
    ViewData["Title"] = "Our Books";
}

<div class="header-actions">
    <div class="search-bar">
        <form asp-action="Index" method="get" class="search-form">
            <i class="fas fa-search search-icon"></i>
            <input type="text"
                   name="searchString"
                   placeholder="Search books..."
                   class="search-input"
                   value="@Context.Request.Query["searchString"]">
        </form>
    </div>
    <a asp-action="Create" class="btn btn-primary create-btn">
        <i class="fas fa-plus"></i> Add New Book
    </a>
</div>

<div class="books-container">
    @foreach (var item in Model)
    {
        <div class="book-card">
            <div class="book-image">
                @if (!string.IsNullOrEmpty(item.PictureUrl))
                {
                    <img src="@item.PictureUrl" alt="@item.Title" />
                }
                else
                {
                    <img src="/images/default-book.jpg" alt="Default book cover" />
                }
                <div class="book-overlay">
                    <a asp-action="Details" asp-route-id="@item.Id" class="overlay-btn">
                        View Details
                    </a>
                </div>
            </div>
            <div class="book-info">
                <h3 class="book-title">@item.Title</h3>
                <div class="book-meta">
                    <span class="book-isbn"><i class="fas fa-barcode"></i> @item.ISBN</span>
                    <span class="book-date"><i class="far fa-calendar-alt"></i> @(item.Date?.ToString("MMM yyyy") ?? "N/A")</span>
                </div>
                <p class="book-description">@(item.Description?.Length > 100 ? item.Description.Substring(0, 97) + "..." : item.Description)</p>
                <div class="book-price-actions">
                    <span class="book-price">$@(item.Price?.ToString("F2") ?? "0.00")</span>
                    <div class="quick-actions">
                        @* <button class="btn btn-sm btn-outline-primary add-to-cart"> *@
                        @*     <i class="fas fa-shopping-cart"></i> *@
                        @* </button> *@
                        @if (User.Identity.IsAuthenticated && (item.UserId == UserManager.GetUserId(User) || User.IsInRole("Admin"))){}
                        <div class="admin-buttons">
                            <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-outline-warning">
                                <i class="fas fa-edit"></i>
                            </a>
                            <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-outline-danger">
                                <i class="fas fa-trash"></i>
                            </a>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
    }
</div>